# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('artista', models.CharField(max_length=140)),
                ('no_canciones', models.IntegerField()),
            ],
        ),
    ]
